# === Common ===

sudo: false

language: cpp


# === Build matrix ===

jobs:
  include:
# Trigger the building of the dependent libs.
    - stage: Trigger downstream
      name: "Trigger downstream"
      if: branch = skipped  # TODO: remove it after fix Windows build with secure vars and add secure var TRAVIS_ACCESS_TOKEN.

      before_install:
        - gem install travis

      script:
        - cp ${TRAVIS_BUILD_DIR}/ci/travis/trigger.sh ${TRAVIS_BUILD_DIR}/
        - cp ${TRAVIS_BUILD_DIR}/ci/travis/trigger-travis.sh ${TRAVIS_BUILD_DIR}/
        - cd ${TRAVIS_BUILD_DIR}

        # LibCMaker   GoogleTest  AGG
        #
        #                         Dirent      FontConfig
        #                         Expat       FontConfig
        #
        #                         HarfBuzz    FreeType    FontConfig
        #
        #                         ICU         Boost
        #                                     SQLite3     SQLiteModernCPP
        #
        #                         Pixman      Cairo
        #                         STLCache
        #                         wxWidgets
        #                         zlib        libpng      Cairo

        # NOTE: LibCMaker lib triggers.
        - ./trigger.sh LibCMaker LibCMaker_GoogleTest master $TRAVIS_ACCESS_TOKEN


notifications:
  email:
    recipients:
      - nfeodonit@yandex.com
    on_success: always
    on_failure: always
